const DictEquip = {
  Juno: {
    name: "Juno",
    type: "Rocket",
    mass: 1,
    thrust: 4,
    cost: 1,
    requires: "Juno",
  },
  Atlas: {
    name: "Atlas",
    type: "Rocket",
    mass: 4,
    thrust: 27,
    cost: 5,
    requires: "Atlas",
  },
  Soyuz: {
    name: "Soyuz",
    type: "Rocket",
    mass: 9,
    cost: 8,
    requires: "Soyuz",
    thrust: 80,
  },
  Saturn: {
    name: "Saturn",
    type: "Rocket",
    mass: 20,
    cost: 15,
    requires: "Saturn",
    thrust: 200,
  },
  Ion: {
    name: "Ion",
    type: "Thruster",
    mass: 1,
    cost: 10,
    requires: "Ion Thrusters",
    impulse: 5,
  },
  Probe: {
    name: "Probe",
    type: "Probe",
    mass: 1,
    cost: 1,
    special: "scan",
  },
  Vestok: {
    name: "Vestok",
    type: "Capsule",
    mass: 2,
    cost: 2,
    requires: "Reentry",
    capacity: 1,
    special: "burn up unless reentry successful",
  },
  Eagle: {
    name: "Eagle",
    type: "Capsule",
    mass: 1,
    cost: 4,
    requires: "Landing",
    capacity: 2,
    special: "burn up on reentry",
  },
  Apollo: {
    name: "Apollo",
    type: "Capsule",
    mass: 3,
    cost: 4,
    requires: "Reentry",
    capacity: 3,
    special: "burn up unless reentry successful",
  },
  Aldrin: {
    name: "Aldrin",
    type: "Capsule",
    mass: 3,
    cost: 4,
    requires: "Life Support",
    capacity: 8,
    special: "burn up on reentry",
  },
  Supplies: {
    name: "Supplies",
    type: "Supplies",
    mass: 1,
    cost: 1,
    requires: "Life Support",
  },
  "Ceres Sample": {
    name: "Ceres Sample",
    type: "Sample",
    mass: 1,
  },
  "Mars Sample": {
    name: "Mars Sample",
    type: "Sample",
    mass: 1,
  },
  "Mercury Sample": {
    name: "Mercury Sample",
    type: "Sample",
    mass: 1,
  },
  "Moon Sample": {
    name: "Moon Sample",
    type: "Sample",
    mass: 1,
  },
  "Phobos Sample": {
    name: "Phobos Sample",
    type: "Sample",
    mass: 1,
  },
  "Venus Sample": {
    name: "Venus Sample",
    type: "Sample",
    mass: 1,
  },
  "Buzz Aldrin": {
    name: "Buzz Aldrin",
    type: "Astronaut",
    cost: 5,
    specialty: "Mechanic",
  },
  "Konstantin Feoktistov": {
    name: "Konstantin Feoktistov",
    type: "Astronaut",
    cost: 5,
    specialty: "Mechanic",
  },
  "Gus Grissom": {
    name: "Gus Grissom",
    type: "Astronaut",
    cost: 5,
    specialty: "Mechanic",
  },
  "Vladimir Komarov": {
    name: "Vladimir Komarov",
    type: "Astronaut",
    cost: 5,
    specialty: "Mechanic",
  },
  "Jim Lovell": {
    name: "Jim Lovell",
    type: "Astronaut",
    cost: 5,
    specialty: "Mechanic",
  },
  "Neil Armstrong": {
    name: "Neil Armstrong",
    type: "Astronaut",
    cost: 5,
    specialty: "Pilot",
  },
  "Yuri Gagarin": {
    name: "Yuri Gagarin",
    type: "Astronaut",
    cost: 5,
    specialty: "Pilot",
  },
  "John Glenn": {
    name: "John Glenn",
    type: "Astronaut",
    cost: 5,
    specialty: "Pilot",
  },
  "Alan Shepard": {
    name: "Alan Shepard",
    type: "Astronaut",
    cost: 5,
    specialty: "Pilot",
  },
  "Joseph Walker": {
    name: "Joseph Walker",
    type: "Astronaut",
    cost: 5,
    specialty: "Pilot",
  },
  "Valery Bykovsky": {
    name: "Valery Bykovsky",
    type: "Astronaut",
    cost: 5,
    specialty: "Medic",
  },
  "Mike Collins": {
    name: "Mike Collins",
    type: "Astronaut",
    cost: 5,
    specialty: "Medic",
  },
  "Gherman Titov": {
    name: "Gherman Titov",
    type: "Astronaut",
    cost: 5,
    specialty: "Medic",
  },
  "Valentina Tereshkova": {
    name: "Valentina Tereshkova",
    type: "Astronaut",
    cost: 5,
    specialty: "Medic",
  },
  "Boris Yegorov": {
    name: "Boris Yegorov",
    type: "Astronaut",
    cost: 5,
    specialty: "Medic",
  },
};

export const arrayEquip = [
  {
    name: "Juno",
    type: "Rocket",
    mass: 1,
    thrust: 4,
    cost: 1,
    requires: "Juno",
  },
  {
    name: "Atlas",
    type: "Rocket",
    mass: 4,
    thrust: 27,
    cost: 5,
    requires: "Atlas",
  },
  {
    name: "Soyuz",
    type: "Rocket",
    mass: 9,
    cost: 8,
    requires: "Soyuz",
    thrust: 80,
  },
  {
    name: "Saturn",
    type: "Rocket",
    mass: 20,
    cost: 15,
    requires: "Saturn",
    thrust: 200,
  },
  {
    name: "Ion",
    type: "Thruster",
    mass: 1,
    cost: 10,
    requires: "Ion Thrusters",
    impulse: 5,
  },
  {
    name: "Probe",
    type: "Probe",
    mass: 1,
    cost: 1,
    special: "scan",
  },
  {
    name: "Vestok",
    type: "Capsule",
    mass: 2,
    cost: 2,
    requires: "Reentry",
    capacity: 1,
    special: "burn up unless reentry successful",
  },
  {
    name: "Eagle",
    type: "Capsule",
    mass: 1,
    cost: 4,
    requires: "Landing",
    capacity: 2,
    special: "burn up on reentry",
  },
  {
    name: "Apollo",
    type: "Capsule",
    mass: 3,
    cost: 4,
    requires: "Reentry",
    capacity: 3,
    special: "burn up unless reentry successful",
  },
  {
    name: "Aldrin",
    type: "Capsule",
    mass: 3,
    cost: 4,
    requires: "Life Support",
    capacity: 8,
    special: "burn up on reentry",
  },
  {
    name: "Supplies",
    type: "Supplies",
    mass: 1,
    cost: 1,
    requires: "Life Support",
  },
  {
    name: "Ceres Sample",
    type: "Sample",
    mass: 1,
  },
  {
    name: "Mars Sample",
    type: "Sample",
    mass: 1,
  },
  {
    name: "Mercury Sample",
    type: "Sample",
    mass: 1,
  },
  {
    name: "Moon Sample",
    type: "Sample",
    mass: 1,
  },
  {
    name: "Phobos Sample",
    type: "Sample",
    mass: 1,
  },
  {
    name: "Venus Sample",
    type: "Sample",
    mass: 1,
  },
  {
    name: "Buzz Aldrin",
    type: "Astronaut",
    cost: 5,
    specialty: "Mechanic",
  },
  {
    name: "Konstantin Feoktistov",
    type: "Astronaut",
    cost: 5,
    specialty: "Mechanic",
  },
  {
    name: "Gus Grissom",
    type: "Astronaut",
    cost: 5,
    specialty: "Mechanic",
  },
  {
    name: "Vladimir Komarov",
    type: "Astronaut",
    cost: 5,
    specialty: "Mechanic",
  },
  {
    name: "Jim Lovell",
    type: "Astronaut",
    cost: 5,
    specialty: "Mechanic",
  },
  {
    name: "Neil Armstrong",
    type: "Astronaut",
    cost: 5,
    specialty: "Pilot",
  },
  {
    name: "Yuri Gagarin",
    type: "Astronaut",
    cost: 5,
    specialty: "Pilot",
  },
  {
    name: "John Glenn",
    type: "Astronaut",
    cost: 5,
    specialty: "Pilot",
  },
  {
    name: "Alan Shepard",
    type: "Astronaut",
    cost: 5,
    specialty: "Pilot",
  },
  {
    name: "Joseph Walker",
    type: "Astronaut",
    cost: 5,
    specialty: "Pilot",
  },
  {
    name: "Valery Bykovsky",
    type: "Astronaut",
    cost: 5,
    specialty: "Medic",
  },
  {
    name: "Mike Collins",
    type: "Astronaut",
    cost: 5,
    specialty: "Medic",
  },
  {
    name: "Gherman Titov",
    type: "Astronaut",
    cost: 5,
    specialty: "Medic",
  },
  {
    name: "Valentina Tereshkova",
    type: "Astronaut",
    cost: 5,
    specialty: "Medic",
  },
  {
    name: "Boris Yegorov",
    type: "Astronaut",
    cost: 5,
    specialty: "Medic",
  },
];

export default DictEquip;
